# https://taskfile.dev

version: "3"

vars:
  OUT_DATASETS: data/raw_datasets

tasks:
  run:
    cmds:
      - python src/main.py

  setup:
    cmds:
      - pip install -r requirements.txt

  install:
    cmds:
      - pip install {{.CLI_ARGS}}

  freeze:
    cmds:
      - pip freeze > requirements.txt

  grpc_gen:
    cmds:
      - ./grpc_code_gen.sh

  dataset:
    cmds:
      - chmod +x ./scripts/download_datasets.sh
      - mkdir -p {{.OUT_DATASETS}}
      - scripts/download_datasets.sh {{.OUT_DATASETS}}
