FROM node:16 AS build

WORKDIR /app

COPY frontend/ ./

RUN npm i -g pnpm \
  && pnpm i \
  && pnpm build

####################################################################

FROM nginx:alpine AS production

WORKDIR /usr/share/nginx/html

COPY .docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
