version: '3.9'

services:
    recommendation:
        container_name: annimendation_recommendation
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        ports:
            - 50051:50051
