# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raw_anime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fraw_anime.proto\x12\x05\x61nime\"\x06\n\x04Void\"\xa0\x03\n\x08RawAnime\x12\x0e\n\x06mal_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x05score\x18\x03 \x01(\x02H\x00\x88\x01\x01\x12\x13\n\x06genres\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rjapanese_name\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04type\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x65pisodes\x18\x07 \x01(\rH\x04\x88\x01\x01\x12\x12\n\x05\x61ired\x18\x08 \x01(\tH\x05\x88\x01\x01\x12\x14\n\x07studios\x18\t \x01(\tH\x06\x88\x01\x01\x12\x13\n\x06source\x18\n \x01(\tH\x07\x88\x01\x01\x12\x13\n\x06rating\x18\x0b \x01(\tH\x08\x88\x01\x01\x12\x17\n\npopularity\x18\x0c \x01(\rH\t\x88\x01\x01\x12\x15\n\x08watching\x18\r \x01(\rH\n\x88\x01\x01\x42\x08\n\x06_scoreB\t\n\x07_genresB\x10\n\x0e_japanese_nameB\x07\n\x05_typeB\x0b\n\t_episodesB\x08\n\x06_airedB\n\n\x08_studiosB\t\n\x07_sourceB\t\n\x07_ratingB\r\n\x0b_popularityB\x0b\n\t_watching\"4\n\x10RawAnimeSynopsis\x12\x0e\n\x06mal_id\x18\x01 \x01(\r\x12\x10\n\x08synopsis\x18\x02 \x01(\t\"C\n\x0eRawAnimeRating\x12\x10\n\x08\x61nime_id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x0e\n\x06rating\x18\x03 \x01(\r2\xc9\x01\n\x0fRawAnimeService\x12\x32\n\x0e\x46\x65tchRawAnimes\x12\x0b.anime.Void\x1a\x0f.anime.RawAnime\"\x00\x30\x01\x12\x42\n\x16\x46\x65tchRawAnimesSynopsis\x12\x0b.anime.Void\x1a\x17.anime.RawAnimeSynopsis\"\x00\x30\x01\x12>\n\x14\x46\x65tchRawAnimeRatings\x12\x0b.anime.Void\x1a\x15.anime.RawAnimeRating\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raw_anime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=26
  _VOID._serialized_end=32
  _RAWANIME._serialized_start=35
  _RAWANIME._serialized_end=451
  _RAWANIMESYNOPSIS._serialized_start=453
  _RAWANIMESYNOPSIS._serialized_end=505
  _RAWANIMERATING._serialized_start=507
  _RAWANIMERATING._serialized_end=574
  _RAWANIMESERVICE._serialized_start=577
  _RAWANIMESERVICE._serialized_end=778
# @@protoc_insertion_point(module_scope)
