# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shutdown.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshutdown.proto\x12\x08shutdown\"\x06\n\x04Void2?\n\x0fShutdownService\x12,\n\x08Shutdown\x12\x0e.shutdown.Void\x1a\x0e.shutdown.Void\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shutdown_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=28
  _VOID._serialized_end=34
  _SHUTDOWNSERVICE._serialized_start=36
  _SHUTDOWNSERVICE._serialized_end=99
# @@protoc_insertion_point(module_scope)
