# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import shutdown_pb2 as shutdown__pb2


class ShutdownServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Shutdown = channel.unary_unary(
            "/shutdown.ShutdownService/Shutdown",
            request_serializer=shutdown__pb2.Void.SerializeToString,
            response_deserializer=shutdown__pb2.Void.FromString,
        )


class ShutdownServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ShutdownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Shutdown": grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=shutdown__pb2.Void.FromString,
            response_serializer=shutdown__pb2.Void.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("shutdown.ShutdownService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ShutdownService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Shutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/shutdown.ShutdownService/Shutdown",
            shutdown__pb2.Void.SerializeToString,
            shutdown__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
