FROM node:16 AS build

WORKDIR /app

COPY frontend/ ./

RUN npm i -g pnpm \
  && pnpm i \
  && pnpm build

###########################################
FROM node:16-alpine AS production

WORKDIR /app

COPY --from=build /app/dist .

EXPOSE 3333

CMD ["node", "server.js"]

